### ISSUE TITLE
how to add language for response address name 

### ISSUE THREAD

**Issue by fahmyabada** [binhlam10796/nominatim_flutter#1]
i want return response according to language app 
how do it

**Comment by binhlam10796** [comment]
Sorry about my lateness, I'm so busy with my personal work.
I haven't added "accept-language" in the header for this version. So, I'm going to add this header in the next version.

**Comment by binhlam10796** [comment]
In version 0.0.3, I have added language support for the returned results. You can experience it now. Thank you
